# Generated by Django 5.0.6 on 2024-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.CharField(default='asas', max_length=50000),
            preserve_default=False,
        ),
    ]
