# Generated by Django 5.0.6 on 2024-05-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0002_remove_post_audio_remove_post_video_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Автор', on_delete=django.db.models.deletion.CASCADE, to='mmo.author'),
        ),
    ]
