# Generated by Django 5.0.6 on 2024-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0002_remove_post_audio_remove_post_video_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
